### PR TITLE
update to datamaps v0.5

### PR DESCRIPTION
**Pull request by gauravarora**

### CODE REVIEW

**Comment by gauravarora** [comment]
The only major change in v0.5 was the addition of high res maps.

**Comment by pfarnach** [comment]
Thanks for the heads up.  Why not go to v0.5.8?

**Comment by gauravarora** [comment]
Wouldn't `~` automatically resolve to `0.5.8`? I can change it if you would like to explicitly see `0.5.8`.

**Comment by pfarnach** [comment]
Yes, you're right.  I usually do exact versioning and missed the "~".  Thanks!

**Pull request merged**
